services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false
    restart: unless-stopped
    volumes:
      - bot-data:/app/data
    networks:
      - solane-run

networks:
  solane-run:
    external: true

volumes:
  bot-data:
